### ISSUE TITLE
Firefox 3.6 compatibility

### ISSUE THREAD

**Issue by AbeEstrada** [choltz/clear-cache-button#1]
Version 0.9b doesn't work with Firefox 3.6
https://addons.mozilla.org/en-US/firefox/addon/1801

**Comment by fnagel** [comment]
+1, please!

**Comment by AbeEstrada** [comment]
Fixed!

**Comment by fnagel** [comment]
This fix does not work for me. Tested on 2 Installations (both Win XP Pro SP3 on newest FF). When i using FF for about 3-4 hours for webdeveloping its usually using 400-600 MB Ram. I push your button and... nothing happens.

Should your extension release memory consumed by plugins?

**Comment by choltz** [comment]
The extension calls the firefox caching api to release memory and disk-based cached resources. Plugin memory consumption can be caused by many things - many are not governed by the Firefox Cache api (example - memory leaks).

Here's how to test whether or not the clear cache button is working:

1) open a tab and in the address bar type in about:cache
2) this will display firefox cache statistics
3) click the clear cache button
4) refresh the about:cache page

you should see the memory and disk cache values drop to zero.

Incidentally - How does the clear cache button aid you in web development? I am always interested in hearing how people use the add-on.
- Chris
